# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d17eb95b31d7f324a920712e0ac2b7b57ff8982f11e596ad6ae8d89fd47a60f6bdf4a66af9a62ad52ef91c26df155d3e9216bd3befa8ebc0529405c001f81955

test:
  secret_key_base: 26a0d0739f7c2f43488d3ca483324692aa207fa2dea3d00b902d923a4ca95967b2e4c5509487edbca4287c6b0a546a96dad840e18f1039632c1a50d31e0113a3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
